apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker/tmp.config convert --chart --controller deployment --service-group-mode label --service-group-name mzai-local-app --out helm/model_builder
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./docker/tmp.config convert --chart --controller deployment --service-group-mode label --service-group-name mzai-local-app --out helm/model_builder
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/mzai-platform-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DEPLOYMENT_TYPE
              value: {{ .Values.DEPLOYMENT_TYPE }}
            - name: POSTGRES_DB
              value: platform
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: admin
            - name: RAY_DASHBOARD_PORT
              value: "8265"
            - name: RAY_HEAD_NODE_HOST
              value: ray
          image: {{ .Values.image }}
          name: backend
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
      restartPolicy: Always
