apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker/tmp.config convert --chart --controller deployment --service-group-mode label --service-group-name mzai-local-app --out helm/model_builder
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres
