name: lumigator

services:
  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lumigator

  minio:
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
    volumes:
      - 'minio-data:/data'

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 minio_user minio_password &&
      mc mb minio/lumigator-storage || true"

  ray:
    image: rayproject/ray:2.30.0-py311-cpu${RAY_ARCH_SUFFIX}
    ports:
      - "6379:6379"
      - "8265:8265"
      - "10001:10001"
    command: bash -c "ray start --head --dashboard-port=8265 --port=6379 --dashboard-host=0.0.0.0 --redis-password=yourpassword --block" # pragma: allowlist secret
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '5g'
    environment:
      - HOST=localhost
      - RAY_IMAGE=raytest
      - REDISPORT=6379
      - DASHBOARDPORT=8265
      - HEADNODEPORT=10001
      - REDISPASSWORD=yourpassword
      - NUM_WORKERS=4
      - NUM_CPU_WORKER=1
      # NOTE: the following path contains a hash which needs to be updated whenever
      # the list of libraries installed in backend/services/experiments.py changes.
      # This is a temporary solution, see https://github.com/mozilla-ai/lumigator/pull/186
      - LD_PRELOAD=/tmp/ray/session_latest/runtime_resources/pip/7d3f1f47289095547ca48bc9a1eaa799900bb4d9/virtualenv/lib/python3.11/site-packages/scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
    volumes:
      - ../lumigator/python/mzai/summarizer/summarizer.py:/home/ray/summarizer.py
    # NOTE: to keep AWS_ENDPOINT_URL as http://localhost:9000 both on the host system
    #       and inside containers, we map localhost to the host gateway IP.
    #       This currently works properly, but might be the cause of networking
    #       issues down the line. This should be used only for local, development
    #       deployments.
    extra_hosts:
      - "localhost:host-gateway"

  backend:
    build:
      context: ..
      dockerfile: ".devcontainer/Dockerfile.backend"
    platform: linux/amd64
    depends_on:
      - postgres
      - minio
    ports:
      - 80:80
    environment:
      - DEPLOYMENT_TYPE=local
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lumigator
      # The local file needs to be available through a mount,
      # if persistence is needed
      - SQLALCHEMY_DATABASE_URL=sqlite:///local.db
      - S3_ENDPOINT_URL=http://localhost:9000
      - AWS_ACCESS_KEY_ID=minio_user
      - AWS_SECRET_ACCESS_KEY=minio_password
      #- AWS_DEFAULT_REGION=us-east-2
      - AWS_ENDPOINT_URL=http://localhost:9000
      - S3_BUCKET=lumigator-storage
      - PYTHONPATH=/mzai/lumigator/python/mzai/backend
      - EVALUATOR_WORK_DIR=/mzai/lumigator/python/mzai/evaluator
      - RAY_DASHBOARD_PORT=8265
      - RAY_HEAD_NODE_HOST=ray
      - LOCAL_FSSPEC_S3_ENDPOINT_URL=${LOCAL_FSSPEC_S3_ENDPOINT_URL}
      - LOCAL_FSSPEC_S3_KEY=${LOCAL_FSSPEC_S3_KEY}
      - LOCAL_FSSPEC_S3_SECRET=${LOCAL_FSSPEC_S3_SECRET}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAY_WORKER_GPUS=0
      - RAY_WORKER_GPUS_FRACTION=0
    volumes:
      - ../:/mzai
    # NOTE: to keep AWS_ENDPOINT_URL as http://localhost:9000 both on the host system
    #       and inside containers, we map localhost to the host gateway IP.
    #       This currently works properly, but might be the cause of networking
    #       issues down the line. This should be used only for local, development
    #       deployments.
    extra_hosts:
      - "localhost:host-gateway"

volumes:
    postgres-data:

    minio-data: