apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ./docker/tmp.config convert --chart --controller deployment --service-group-mode label --service-group-name mzai-local-app --out helm/model_builder
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: backend
