name: SDK Packaging

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    tags:
    # Not the right semver regexp, but good enough
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  sdk-packaging:
    name: Package SDK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install python
        run: uv python install
        working-directory: lumigator/python/mzai/sdk

      - name: Package SDK
        run: uv build
        working-directory: lumigator/python/mzai/sdk

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: SDK packages
          path: |
            lumigator/python/mzai/sdk/dist/*.whl
            lumigator/python/mzai/sdk/dist/*.tar.gz